apiVersion: v1
kind: ServiceAccount
metadata:
  name: drop

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drop
rules:
  # Sources read
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drop
subjects:
  - kind: ServiceAccount
    name: drop
    namespace: default
